
import java.util.Calendar;
import java.util.Date;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author praty
 */
public class admin_register extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
    public admin_register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        txtname = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        txtusername = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtrepass = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        dob = new datechooser.beans.DateChooserCombo();
        jSeparator1 = new javax.swing.JSeparator();
        back = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Admin Registration Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 480, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Full Name  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 150, -1));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Gender   :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("Email-Id  :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, -1));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("User Name  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 160, -1));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Password  :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, -1));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("Retype Pass  :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, -1));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Mobile Number :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, -1));

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 260, 90));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 290, 30));

        txtmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 290, 30));

        female.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 93, -1));

        male.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setSelected(true);
        male.setText("Male");
        male.setOpaque(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 70, -1));

        txtusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 290, 30));

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 290, 30));

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 290, 30));

        txtrepass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtrepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 290, 30));

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("Address    :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 140, -1));

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 240, 60));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Birth Date  :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 150, -1));

        dob.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dob.setCalendarBackground(new java.awt.Color(204, 204, 204));
    dob.setNothingAllowed(false);
    dob.setFormat(0);
    dob.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 15));
    dob.setMaxDate(new java.util.GregorianCalendar(2021, 5, 30));
    dob.setMinDate(new java.util.GregorianCalendar(1985, 5, 11));
    dob.setNavigateFont(new java.awt.Font("SimSun-ExtB", java.awt.Font.BOLD, 15));
    jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 260, 30));

    jSeparator1.setForeground(new java.awt.Color(0, 0, 204));
    jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 630, -1));

    back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    back.setText("Back");
    back.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backActionPerformed(evt);
        }
    });
    jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 100, -1));

    back1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    back1.setText("Clear");
    back1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            back1ActionPerformed(evt);
        }
    });
    jPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, -1, -1));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 640, 580));

    jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\praty\\OneDrive\\Desktop\\registration.jpg")); // NOI18N
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String name=(txtname.getText()).toUpperCase();
        String mail=txtmail.getText().toLowerCase();
        String use=txtusername.getText();
        String pas=txtpass.getText();
        String repass=txtrepass.getText();
        String birth = dob.getText();
        //String birth=String.valueOf(dt);
        System.out.println(birth);
       // SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");
       // String date=f.format(dt);
       
        if(!pas.equals(repass))
        {
            JOptionPane.showMessageDialog(this,"Password Not Matched");
        }
        else
        {
           
        pas=repass;
        String  mob=txtmobile.getText();
        String add=txtaddress.getText().toUpperCase();
     // Date birth=dob.();
        String gen="";
        if(male.isSelected()==true)
        {
            gen="male";
        }
        else
        {
            gen="female";
        }
       
           if(name.equals("")||mail.equals("")||use.equals("")||pas.equals("")||repass.equals("")||mob.equals("")||add.equals(""))
               
        {
            JOptionPane.showMessageDialog(this,"Please fill all the details");
            this.setVisible(true);
        }
           else{
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
       
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Pratyush@8055")) {
                String s="insert into admin_details(name,email,password,address,user_name,gender,mobile,dob) values(?,?,?,?,?,?,?,?)";
                PreparedStatement st = con.prepareStatement(s);
                         
                st.setString(1,name);
                st.setString(2,mail);
                st.setString(3,pas);
            //    st.setDate(4,birth);
                st.setString(4,add);
                st.setString(5,use);
                st.setString(6,gen);
                st.setString(7,mob);
                st.setString(8,birth);
                
                
                int a=st.executeUpdate();
               
                if(a>0)
                {
                    JOptionPane.showMessageDialog(this,"You are Successfully Registered");
                       new adminLogin().setVisible(true);
                       this.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Invalid Details");
                    txtusername.setText("");
                    txtname.setText("");
                    
                }
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           }
        
        }
        
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        if(male.isSelected())
        {
            female.setSelected(false);
        }
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:

        if(female.isSelected())
        {
            male.setSelected(false);
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new adminLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        txtname.setText("");
        txtmail.setText("");
         txtusername.setText("");
        txtpass.setText("");
         txtrepass.setText("");
        txtmobile.setText("");
         txtaddress.setText("");
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton btnsubmit;
    private datechooser.beans.DateChooserCombo dob;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtrepass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
