
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author praty
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
      
    public bill() {
        initComponents();
        int pn=com.configure.Record.getPnr();
    String path="";
        ArrayList<String> a=new ArrayList<String>();
        try
                    {
                        Connection con=com.configure.Record.takeConnection();
                        String s="select passenger.*,bus_details.bus_no,bus_details.time,bus_details.type from passenger,bus_details where pnr_no=? and passenger.bus_id=bus_details.bus_id";
                        PreparedStatement st = con.prepareStatement(s);
                        st.setInt(1,pn);
                        ResultSet rs=st.executeQuery();
                        if(rs.next())
                        {
                            a.add(rs.getString(1));
                            a.add(rs.getString(2));
                            a.add(rs.getString(3));
                            a.add(rs.getString(4));
                            a.add(rs.getString(5));
                            a.add(rs.getString(6));
                            a.add(rs.getString(7));
                            a.add(rs.getString(8));
                          a.add(rs.getString(9));
                           a.add(rs.getString(10));
                            a.add(rs.getString(11));
                             a.add(rs.getString(12));
                              a.add(rs.getString(13));
                                a.add(rs.getString(14)); 
                                a.add(rs.getString(15));
                                
                              
                            
                        }
                        con.close();
                    }
                    catch (Exception e) 
                    {
                        e.printStackTrace();
                    }
               if(a.size()!=0)
               {
                   pnr.setText(a.get(0));
                   name.setText(a.get(1));
                   number.setText(a.get(2));
                   dest.setText(a.get(3));
                    mobile.setText(a.get(4));
                     cat.setText(a.get(5));
                      idno.setText(a.get(6));
                       date.setText(a.get(8));
                       busno.setText(a.get(12));
                       time.setText(a.get(13));
                      bustype.setText(a.get(14));
                      path=a.get(7);
               }
               
               
               // Image img=image.getScaledInstance(limg.getWidth(),limg.getHeight(), Image.SCALE_SMOOTH);
                
		ImageIcon img_ico=new ImageIcon(path);
                limg.setIcon(img_ico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        dest = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        cat = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        idno = new javax.swing.JLabel();
        pnr = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        busno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bustype = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        limg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton1.setText("Print Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 190, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 120, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 80, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 255,200));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 19, -1, 33));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Destination:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("No. of Pess:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 58, -1, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mobile No:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 141, -1, 33));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ID Category:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 185, -1, 33));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ID No:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 229, -1, 33));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Date:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 273, -1, 33));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("PNR No.:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, 33));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Bus Time:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 33));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("BUS Type:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 26));

        number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 58, 196, 33));

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 19, 196, 33));

        dest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(dest, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 97, 196, 33));

        mobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 141, 196, 33));

        cat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 196, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 273, 196, 33));

        idno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(idno, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 229, 196, 33));

        pnr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(pnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 130, 33));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 196, 33));

        busno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(busno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 150, 33));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("BUS No:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 26));

        bustype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(bustype, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 180, 30));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(limg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 140));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 200, 140));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 520, 420));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Patna Bus Stand");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setText("Gandhi Maidan,Patna,Bihar-80001");

        jPanel2.setForeground(new java.awt.Color(0, 0, 0,0));
        jPanel2.setPreferredSize(new java.awt.Dimension(66, 66));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\praty\\OneDrive\\Desktop\\logofinal.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 83));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\praty\\OneDrive\\Desktop\\bus-conductor.jpg")); // NOI18N
        jLabel1.setText("Back");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 580, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
           printTicket(jPanel4);      
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
        new passengers(1001,"Pratyush").setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
 private void printTicket(JPanel panel)
    {
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName("Print Ticket");
        pj.setPrintable(new Printable() {
            //@Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             if(pageIndex>0)
             {
                 return Printable.NO_SUCH_PAGE;
             }

             Graphics2D g = (Graphics2D) graphics;
             g.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
             g.scale(0.5,0.5);
             panel.paint(g);
             return Printable.PAGE_EXISTS;
            }
        });

        boolean res = pj.printDialog();
        if(res)
        {
            try
            {
                pj.print();
            }
            catch(PrinterException e)
            {
                JOptionPane.showMessageDialog(this,"Printer Erro: "+e);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busno;
    private javax.swing.JLabel bustype;
    private javax.swing.JLabel cat;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dest;
    private javax.swing.JLabel idno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel limg;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JLabel number;
    private javax.swing.JLabel pnr;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
