
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import com.configure.Record;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author praty
 */
public class passengers extends javax.swing.JFrame {

    /**
     * Creates new form passengers
     */
    int vandor_id=0;String naam="";
    public passengers(int vid,String na) {
        vandor_id=vid;
        naam=na;
        if(vandor_id!=0&&naam!=""){
        initComponents();
        fillCombo();
        txtvendor1.setText("Login with: "+vandor_id);
        txtvname.setText(naam);
        }
    }
    public void fillCombo(){
      
                    try
                    {
                        Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Pratyush@8055");
                        String s="select distinct destination from bus_details";
                      PreparedStatement st = con.prepareStatement(s);
                        ResultSet rs=st.executeQuery(s);
                        while(rs.next())
                        {
                            String cat=rs.getString("destination");
                           destination.addItem(cat);
                        }
                        st.executeUpdate();
                        con.close();
                    }
                    catch (Exception e) 
                    {
                        e.printStackTrace();
                    }
    }

    passengers() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        sNoPass = new javax.swing.JSpinner();
        txtmobile = new javax.swing.JTextField();
        category = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtidno = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        generate = new javax.swing.JButton();
        upload = new javax.swing.JButton();
        choose = new javax.swing.JButton();
        txtvname = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtvendor1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        destination = new javax.swing.JComboBox<>();
        back1 = new javax.swing.JButton();
        back2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Passenger Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 19, 401, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 121, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("No. Of Passengers:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Destination:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 205, -1, -1));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Mobile:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("ID Category:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 28));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 190, 30));

        sNoPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sNoPass.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        sNoPass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sNoPass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sNoPassStateChanged(evt);
            }
        });
        jPanel1.add(sNoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 80, 30));

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 190, 27));

        category.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aadhar Card","Voter ID", "Pan Card", "Driving License", "Passport" }));
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 190, 30));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("ID Number:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 28));

        txtidno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 190, 30));

        jTextField4.setText("jTextField4");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 570, 189, 62));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 590, -1, -1));

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(255, 255, 255));
        txttotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 560, 80));

        generate.setBackground(new java.awt.Color(51, 255, 51));
        generate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        generate.setText("Save Details");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        jPanel1.add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 180, 60));

        upload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        upload.setText("Take Picture");
        upload.setEnabled(false);
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        jPanel1.add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 130, 30));

        choose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        choose.setText("Open Camera");
        choose.setEnabled(false);
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        jPanel1.add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 130, 30));

        txtvname.setBackground(new java.awt.Color(255, 102, 102));
        txtvname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtvname.setForeground(new java.awt.Color(51, 255, 255));
        txtvname.setEnabled(false);
        jPanel1.add(txtvname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, 30));

        txtvendor1.setBackground(new java.awt.Color(255, 102, 102));
        txtvendor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtvendor1.setForeground(new java.awt.Color(51, 255, 255));
        txtvendor1.setEnabled(false);
        jPanel1.add(txtvendor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 180, 140));

        destination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 190, 30));

        back1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back1.setText("Preview");
        back1.setEnabled(false);
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 160, 50));

        back2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back2.setText("Clear");
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });
        jPanel1.add(back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 620, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\praty\\OneDrive\\Desktop\\passenger.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String spinner_value=null;
    private void sNoPassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sNoPassStateChanged
        // TODO add your handling code here:
       spinner_value=""+((JSpinner)evt.getSource()).getValue();
        
        
    }//GEN-LAST:event_sNoPassStateChanged

  
    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
   
        String name=txtname.getText().toUpperCase();
        String idno=txtidno.getText();
        String mob=txtmobile.getText();
        String cat=category.getItemAt(category.getSelectedIndex()).toUpperCase();
        String dest=destination.getItemAt(destination.getSelectedIndex()).toUpperCase();
        String bus_amount = Record.getBusAmount(dest);
        double total=Math.round(Double.parseDouble(spinner_value) * Double.parseDouble(bus_amount));
        Date dt = new Date();
        SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");
        String date=f.format(dt);
       
        
        
        
        
        
          if(name != null&&mob != null&&idno != null)
          {
              
              
              try {
                  Class.forName("com.mysql.cj.jdbc.Driver");
                  
                  try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Pratyush@8055")) {
                      String s="insert into passenger(name,nopassenger,destination,date,mobile,id_category,id_number,amount,bus_id,vendor_id) values(?,?,?,?,?,?,?,?,?,?)";
                      PreparedStatement st = con.prepareStatement(s);
                      
                      st.setString(1,name);
                      st.setString(2,String.valueOf(spinner_value));
                      st.setString(3,dest);
                      st.setString(4,date);
                      st.setString(5,mob);
                      st.setString(6,cat);
                      st.setString(7,idno);
                      st.setString(8,String.valueOf(total));
                      st.setInt(9,Record.getBusId(dest));
                      st.setInt(10,vandor_id);
                    
                      
                      
                      int a=st.executeUpdate();
                      
                      if(a>0)
                      {
                          JOptionPane.showMessageDialog(this,"Data Inserted Successfully");
                          txttotal.setText("Total Amount ="+total);
                          
                          
                      }
                      else
                      {
                          JOptionPane.showMessageDialog(this,"Invalid Details");
                          
                      }
                      con.close();
                      choose.setEnabled(true);
                  }
                  
              } catch (ClassNotFoundException | SQLException ex) {
                  Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
           else
          {
              JOptionPane.showMessageDialog(this,"Please fill all the details");
              this.setVisible(true);   
          }                   
        
    }//GEN-LAST:event_generateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
JFrame window = new JFrame("Test webcam panel");
    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
        // TODO add your handling code here:
  
		Webcam webcam = Webcam.getDefault();
		webcam.setViewSize(WebcamResolution.VGA.getSize());

		WebcamPanel panel = new WebcamPanel(webcam);
		panel.setFPSDisplayed(true);
		panel.setDisplayDebugInfo(true);
		panel.setImageSizeDisplayed(true);
		panel.setMirrored(true);
                panel.setBounds(0,0,200,140);
               
		
		window.add(panel);
		window.setResizable(true);
		window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		window.pack();
		window.setVisible(true);
                upload.setEnabled(true);
 	
    }//GEN-LAST:event_chooseActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
	
                try
                {
		Webcam webcam = Webcam.getDefault();
		webcam.open();

		// get image
		BufferedImage image = webcam.getImage();
                Image img=image.getScaledInstance(limage.getWidth(),limage.getHeight(), Image.SCALE_SMOOTH);
                webcam.close();

		// save image to PNG file
                  int pnr=Record.getPnr();
                  String path="C:/Users/praty/Documents/NetBeansProjects/Bus Ticketing Service/src/Image/"+txtname.getText()+pnr+".png";
                ImageIO.write(image, "PNG" , new File(path));
		ImageIcon img_ico=new ImageIcon(img);
                limage.setIcon(img_ico);
                window.setVisible(false);
              Record.setPhoto(path, pnr);
              back1.setEnabled(true);
                }
                catch(Exception e)
                {
                }
    }//GEN-LAST:event_uploadActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        new bill().setVisible(true);
        this.setVisible(false);
        
       
    }//GEN-LAST:event_back1ActionPerformed

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
        // TODO add your handling code here:
         txtname.setText("");
        txtidno.setText("");
        txtmobile.setText("");
        sNoPass.setValue(0);
    }//GEN-LAST:event_back2ActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[])
{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new passengers().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back1;
    private javax.swing.JButton back2;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JButton choose;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton generate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel limage;
    private javax.swing.JSpinner sNoPass;
    private javax.swing.JTextField txtidno;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttotal;
    private javax.swing.JLabel txtvendor1;
    private javax.swing.JLabel txtvname;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
